myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

app_name='myapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('book/<int:book_id>/',views.detail,name='detail'),
    path('add/',views.add_book,name='add_book'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

mysite/urls.py
from xml.dom.minidom import Document
from django.conf import settings
from django.contrib import admin
from django.urls import path
from myapp import views
from django.urls import path, include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.

class Book(models.Model):
    def __str__(self):
        return self.name
    name =models.CharField(max_length=100)
    desc =models.CharField(max_length=300)
    price =models.IntegerField()
    book_image=models.ImageField(default = 'default.jpg',upload_to='book_images/')

myapp/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name','desc','book_image','price']

myapp/views.py
from django import http
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import is_valid_path
from .models import Book
from .forms import BookForm
# Create your views here.

def index(request):
    book_list= Book.objects.all()
    context={
        'book_list':book_list
    }
    return render(request,'myapp/index.html',context)


def detail(request,book_id):
    book = Book.objects.get(id=book_id)
    return render(request, 'myapp/detail.html',{'book':book})

def add_book(request):
    if request.method == 'POST':
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        price = request.POST.get('price',)
        book_image = request.FILES['book_image'] 

        book=Book(name=name,desc=desc,price=price,book_image=book_image)
        book.save()
    return render(request,'myapp/form.html')

def update(request,id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance = book)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'myapp/edit.html',{'form':form,'book':book})

def delete(request,id):
    if request.method == 'POST':
        book=Book.objects.get(id=id)
        book.delete()
        return redirect('')
    return render(request,'myapp/delete.html')

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    <title>Homepage</title>

</head>

<body>

    <nav class="navbar navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                Modern Dairy and Provision Store
            </a>
        </div>
    </nav>

    {% block body%}

    {% endblock%}


</body>

</html>

myapp/templates/myapp/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this book?
    <input type="submit">
</form>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html'%}


{%block body%}
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <img src="{{book.book_image.url}}" height="350" width="400">
        </div>

        <div class="col-lg-6">
            <h2>{{book.name}} </h2>
            <h4>{{book.desc}} </h4>
            <h6>{{book.price}}</h6>
            <a class='btn btn-primary' href="{% url 'myapp:update' book.id %}">Update</a>
            <a class='btn btn-danger' href="{% url 'myapp:delete' book.id %}">Delete</a </div>
        </div>
    </div>



    
    
    {% endblock %}

myapp/templates/myapp/edit.html
{% extends 'myapp/base.html'%}


{%block body%}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        {{form.as_p}}
        <input type="submit">
    </form>
{% endblock %}

myapp/templates/myapp/form.html
{% extends 'myapp/base.html'%}


{%block body%}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token%}
        <input type="text" name="name" id="name" placeholder="Enter name of the book"><br>
        <input type="text" name="desc" id="desc" placeholder="Enter book description"><br>    
        <input type="text" name="price" id="price" placeholder="Enter book price"><br>
        <input type="file" name="book_image" placeholder="Select book image"><br>
        <input type="Submit">
    </form>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html'%}


{%block body%}

<div class='container '>

  <div class="row">
    {% for book in book_list %}
    <div class="col-xl-3 col-lg-4 col-md-6 d-flex justify-content-center">
      <div class="card p-1 m-1 " >
        <img class="card-img-top" src="{{book.book_image.url}}" alt="Card image cap" width="320" height="270">
        <div class="card-body">
          <h5 class="card-title">{{book.name}}</h5>
          <p class="card-text">{{book.desc}}</p>
          <a href="{%url 'myapp:detail' book.id%}" class="btn btn-primary">Details</a>

        </div>
      </div>


    </div>
    {%endfor%}
  </div>

</div>






{% endblock %}